### ISSUE TITLE
Is 'callipygian' an appropriate adjective?

### ISSUE THREAD

**Issue by burchill** [rladies/praise#54]
"Callipygian" basically means "having a nice ass."  While I *personally* think it's funny, I'm not sure if it's something that should be in a general-purpose praising package.

I can imagine someone using the `praise` package in a classroom, for example.  All it would take is for a student to look up the definition of "callipygian," and what was supposed to be humorous just became a sexual harassment case. 

Perhaps it would go better in a `dirtytalk` package?

**Comment by gaborcsardi** [comment]
Thanks! Agreed. Do you want to submit a PR?

**Comment by burchill** [comment]
Yep. Here it is: #55

**Comment by gaborcsardi** [comment]
Thanks!
